### ISSUE TITLE
negative numbers

### ISSUE THREAD

**Issue by mfiano** [Fanael/highlight-numbers#11]
Negatives are highlighted corectly in emacs-lisp-mode, but not in lisp-mode as with Scheme or Common Lisp code buffers.

**Comment by Fanael** [comment]
That's because highlight-numbers doesn't know the correct regexp to use for non-Emacs Lisps, so it defaults to the generic one. Could you post regexps that correctly recognize numbers in non-Emacs Lisps?

**Comment by mfiano** [comment]
I don't see how a regexp can help. It's literally `-1` etc that are not highlighted in this major-mode.

**Comment by Fanael** [comment]
> I don't see how a regexp can help.

How do you think highlight-numbers works?
