### ISSUE TITLE
Characters following numbers

### ISSUE THREAD

**Issue by nicon-git** [Fanael/highlight-numbers#13]
Hello Fanael,
There is an issue in lisp-mode. I found out by accident that If a character follows a number, it's highlighted with the same color as well. That doesn't happens in emacs-lisp-mode. Also, when use the { } brackets the numbers aren't highlighted at all.

Thank you very much.
nicon

**Comment by Fanael** [comment]
That's because highlight-numbers doesn't know about `lisp-mode` (but it does about `emacs-lisp-mode`), so it falls back to `highlight-numbers-generic-regexp` that kinda works most of the time, but in some modes causes issues like the one you've reported.

The fix would be to add a number-matching regexp specifically for `lisp-mode`. I'd gladly merge a PR adding that, but I don't feel knowledgeable enough about Common Lisp to do it myself.

**Comment by nicon-git** [comment]
I'm a newbie in CL's world and i'm struggling to set things up, regarding Emacs and CL. So, i'm not in a position to help with a PR right now. I don't even know how set a regexp. But if i may, i want to ask you something since you're look like an experienced programmer:

The last month i'm trying to setup Emacs, to work beautifully with CL. I've tried numerous of packages regarding UI interaction (highlight, syntax, quoting etc.) and almost all have one thing in common: They're all written for emacs-lisp-mode and if you hook lisp-mode or common-lisp-mode those packages are supporting you partially or not-at-all.

I don't get it though: Emacs is #1 choice for Common Lisp users, it has it's own Lisp dialect, communicating seamlessly via SLIME with Common Lisp and advertised itself and by the CL community as the "workhorse" development env.  I believe this is true since the other communities (the C's, Perl, Clojure etc.) has also other popular choices regarding Editors. And yet, from my little experience, i'm seeing most of the  packages are supporting emacs-lisp rather than common-lisp-mode.

Am i missing something here? Is emacs-lisp so popular among lisp's and i have made the wrong decision to begin learn common lisp?

Thank you very much
nicon

**Comment by Wilfred** [comment]
Well, all Emacsers use elisp, but not all use Common Lisp :)

Still, it's a straightforward addition (`rx` is a lovely way to write regular expressions), so I've opened a PR.
