### ISSUE TITLE
Very slow line movement

### ISSUE THREAD

**Issue by ronisbr** [Fanael/highlight-numbers#18]
Hi!

First of all, thanks for this amazing package!

I am having some problems when I open a file with a lot of numbers and `highlight-numbers-mode` is active. The line movement becomes very, very slow (up and down).

Here is the file I am having problems: https://github.com/JuliaSpace/SatelliteToolbox.jl/blob/master/src/earth/geomagnetic_field_models/igrf/igrf_coefs.jl

Notice that I am not sure if this is something that can be improved or a limitation of Emacs itself.

**Comment by Fanael** [comment]
I couldn't reproduce it with my config, even on a Pentium III laptop where scrolling is already slow, enabling `highlight-numbers-mode` has very little impact. Does the problem occur if you run `emacs -Q` and load only `julia-mode` and `highlight-numbers`?

**Comment by miradnanali** [comment]
Works fine on Emacs 27 under X11.  I saw this problem under versions 25 and 26, related also to text scaling (which worked fine in 24 and early 25 releases).  Moving over to the unstable snapshot version 27 fixed this, among other things.  Your example file works fine there.

**Comment by ronisbr** [comment]
Hum, I am using Emacs 27 here. The problem is reproduced if I only use highlight-numbers and julia-mode.

What I saw is that the performance is good if I use the terminal but bad if I use the GUI. Thus, maybe it is something that only happens in macOS. Are you using the GUI ou the TUI?

**Comment by ronisbr** [comment]
@Fanael I'm sorry! It turns out that when I load the file to load `highlight-numbers-mode`, it was also setting three things: line numbers, trailing whitespaces, and smooth scrolling. When I enable `highlight-numbers-mode` using those two settings, then everything is very slow. Sorry for the noise.
