### ISSUE TITLE
Add global entry?

### ISSUE THREAD

**Issue by jcs090218** [Fanael/highlight-numbers#19]
I think it would be nice if there is `global-highlight-numbers-mode`? Thanks!

**Comment by Fanael** [comment]
`highlight-numbers` is probably not something that makes sense for text modes and other non-code modes, so I'm not going to provide a globalized minor mode; that being said, if you want to have it anyway, it's just a small bit Emacs Lisp that you can add to your own config:
```emacs-lisp
(define-globalized-minor-mode global-highlight-numbers-mode highlight-numbers-mode
  (lambda () (highlight-numbers-mode)))
```
