### ISSUE TITLE
Numbers without spaces aren't highlighted in JS

### ISSUE THREAD

**Issue by Wilfred** [Fanael/highlight-numbers#2]
``` js
// This is highlighted:
foo(x - 1);
// This is not:
foo(x-1);
```

**Comment by mydearxym** [comment]
@Fanael  js-mode works fine , but web-mode or react-mode (in spacemacs)  not work

can you add support for web-mode ?

**Comment by Fanael** [comment]
No, because highlight-numbers itself works correctly in web-mode. It's web-mode that breaks the highlighting done by highlight-numbers. Since I'm not the maintainer of web-mode, I'm entirely the wrong person to ask.
