### ISSUE TITLE
Change the colors/font type? 

### ISSUE THREAD

**Issue by ReneFroger** [Fanael/highlight-numbers#3]
Hi Fanael, I appreciated this package, it's really useful for me. So thanks for that. However, when I would like to change something, I opened the source code of highlight-numbers.el. 

But I couldn't find the values that set the color red, and the numbers to be normal instead bold. I couldn't figure out which faces it uses. 

Any suggestion on this?

**Comment by Fanael** [comment]
Try [reading the README](https://github.com/Fanael/highlight-numbers/blob/master/README.md#customization).
