### ISSUE TITLE
Support -1

### ISSUE THREAD

**Issue by sooheon** [Fanael/highlight-numbers#5]
Maybe there should be a variable to enable this on a per-mode basis, as you wouldn't want to highlight the `-1` of `x-1` in some languages, but in others `-` is never a binary operator, and when it precedes a number is always a part of that number.

**Comment by Fanael** [comment]
highlight-numbers already does so in emacs-lisp-mode, so it's perfectly capable of that. What you're really asking for is adding more definitions to `highlight-numbers-modelist`; please open a pull request adding a definition for whatever language it is you're interested in.
