### ISSUE TITLE
highlights numbers inside strings after saving buffer in js2-mode

### ISSUE THREAD

**Issue by CSRaghunandan** [Fanael/highlight-numbers#9]
here is a screenshot of the bug:
<img width="557" alt="screen shot 2017-02-14 at 14 09 23" src="https://cloud.githubusercontent.com/assets/5226809/22921359/43a5a234-f2bf-11e6-97cf-6cc4a444f8ab.png">

and also highlights numbers inside comments.
PS. this only happens after I save the buffer.

**Comment by Fanael** [comment]
Does it happen in `emacs -Q`, with only highlight-numbers and js2-mode loaded? I can't seem to reproduce it here.

**Comment by CSRaghunandan** [comment]
Umm I can't reproduce the problem in `emacs -Q`

but now I discovered that even opening a .js file like the one above, will highlight the numbers inside the string. But only in the visible part of the buffer. Other parts of the buffer don't highlight numbers inside string(this is weird?). Also, I was using `web-beautify` to format `.js` buffers on save, I guess it caused `js2-mode` to reparse the file everytime I save it and after that, I get the same problem.

I've no idea what I have enabled which could be causing `highlight-numbers` to break for `js2-mode`. It doesn't happen with any other major modes.

**Comment by Fanael** [comment]
> Umm I can't reproduce the problem in `emacs -Q`

So the problem likely lies somewhere in your personal config. I'm unable to help you with that, I can only suggest bisecting your config to find the actual culprit.

One last thing to try, though: could you eval this and reenable highlight-numbers-mode?
```emacs-lisp
(defun highlight-numbers--turn-on ()
  "Set up `highlight-numbers-mode'."
  (let ((regexp (highlight-numbers--get-regexp-for-mode major-mode)))
    (when regexp
      (font-lock-add-keywords nil regexp t)
(set (make-local-variable 'highlight-numbers--keywords) regexp))))
```
This isn't supposed to change the observable behavior here, but if it does, I suspect some package doing some seriously weird things with font-lock.

**Comment by CSRaghunandan** [comment]
@Fanael  I evaluated the code and re-enabled highlight-numbers-mode and I still have the same problem :( 
Unfortunately, I've no idea which package might be messing with font-lock. I tried bisecting, but failed to identify the problematic package.

**Comment by Fanael** [comment]
At any rate, doesn't seem to actually be a bug in highlight-numbers.

**Comment by CSRaghunandan** [comment]
@Fanael  I evaluated the code and re-enabled highlight-numbers-mode and I still have the same problem :( 
Unfortunately, I've no idea which package might be messing with font-lock. I tried bisecting, but failed to identify the problematic package.
